[app]
RunMode = "debug"
PageSize = 10
JwtSecret = "23347$040412"

[server]
HttpPort = 8000
ReadTimeout = 60
WriteTimeout = 60

[database]
Type = "mysql"
User = "root"
Password = "root"
Host = "127.0.0.1:3306"
Name = "blog"
TablePrefix = "blog_"

[log]
LogSavePath = "logs/"
LogSaveName = "log"
LogFileExt = "log"
TimeFormat = "20060102"