[app]
runMode = "debug"
pageSize = 10
jwtSecret = "23347$040412"
prefixUrl = "http://127.0.0.1:8000"

[server]
httpPort = 8000
readTimeout = 60
writeTimeout = 60

[database]
type = "mysql"
user = "root"
password = "root"
host = "127.0.0.1:3306"
name = "blog"
tablePrefix = "blog_"

[log]
logSavePath = "runtime/logs/"
logSaveName = "log"
logFileExt = "log"
timeFormat = "20060102"

[image]
savePath = "runtime/upload/images/"
allowExts = [".jpg", ".jpeg", ".png"]
# MB
maxSize = 5

[redis]
host = "127.0.0.1:6379"
password = "root"

[excel]
savePath = "runtime/excel/"

