[app]
runMode = "debug"
pageSize = 10
jwtSecret = "23347$040412"
prefixUrl = "http://127.0.0.1:8000"

[server]
httpPort = 8000
readTimeout = 60
writeTimeout = 60

[database]
type = "mysql"
user = "root"
password = "xx"
host = "xx"
name = "blog"

[log]
logSavePath = "runtime/logs/"
logSaveName = "log"
logFileExt = "log"
timeFormat = "20060102"

[image]
savePath = "runtime/upload/images/"
allowExts = [".jpg", ".jpeg", ".png"]
# MB
maxSize = 5
smToken = "11idykcqWOkj6VUqO8pX5Fv4OUAKa7vL"

[redis]
host = "xx"
password = "xx"

[excel]
savePath = "runtime/excel/"

